### ISSUE TITLE
Content no longer centered when creating a new user

### ISSUE THREAD

**Issue by pvanlaet** [openmotics/gateway-frontend#16] opened 2016-12-05 21:39 UTC
The login page content is nicely centered vertically and horizontally. After clicking the `Create new user` link this is no longer the case (scrolling is needed to see the bottom of the page).
![image](https://cloud.githubusercontent.com/assets/7603855/20903444/95d09246-bb3b-11e6-8fcc-954f1891e5be.png)

![image](https://cloud.githubusercontent.com/assets/7603855/20903440/8ea635a2-bb3b-11e6-8fed-02ba71b36f9e.png)

**Comment by khenderick** [comment] 2016-12-12 19:26
A lot of browsers these days like to lock their scroll position when content is changed dynamically (which is the case here), so this would mean that:
* If there's no scrollbar available, the new content will be scrolled to top
* If there is a scrollbar, new content will be added, but the scroll position should be equal.

Can you check this behavior? I'd rather keep a browser's behavior instead of explicitly repositioning content after a short while to force a certain behavior different from a browser's default.

**Comment by pvanlaet** [comment] 2016-12-12 21:01
I'm not following :)
The 2 screenshots show the exact behavior of my Firefox instance (only user interaction was clicking the link, no scrolling involved): when `create new user` is clicked the new content is "added" at the bottom and a vertical scrollbar becomes visible. Same behavior on IE.
Is this the default/expected behavior?

**Comment by khenderick** [comment] 2016-12-12 21:19
I suspect that it's the browser's default behavior, called [scroll anchoring](https://developers.google.com/web/updates/2016/04/scroll-anchoring).  If you would decrease the height of your browser, so the login screen has a small scrollbar, and you scroll to the bottom, I would expect that when clicking the link, the content moves up.

Basically making sure that whatever you interact with, keeps on the same spot even when contents change.

**Comment by khenderick** [comment] 2016-12-16 20:27
As discussed, I'm going to close this as I think we can consider this as intended behavior.

**Closed by khenderick** 2016-12-16 20:27 UTC
Labels: enhancement
